sonar.projectKey=Eng-MMustafa_nest-scramble
sonar.organization=eng-mmustafa

sonar.projectName=nest-scramble
sonar.projectVersion=3.0.5

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=src/examples/**,src/controllers/DemoController.ts,dist/**,node_modules/**,coverage/**

sonar.coverage.exclusions=src/examples/**,src/controllers/DemoController.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
