/** Nest-Scramble | Developed by Mohamed Mustafa | MIT License **/
import { ControllerInfo, MethodInfo, ParameterInfo } from '../scanner/ScannerService';
import { AnalyzedType } from '../utils/DtoAnalyzer';

/**
 * Generates a fully-typed TypeScript HTTP client from scanned NestJS controllers.
 * The output file uses native fetch, has zero runtime dependencies, and stays in sync
 * with your controllers by re-running the CLI.
 */
export class TypedClientGenerator {
  constructor(private readonly baseUrl: string = 'http://localhost:3000') {}

  generate(controllers: ControllerInfo[], version = '3.0.4'): string {
    const lines: string[] = [];

    lines.push(`// Auto-generated by nest-scramble v${version} — do not edit manually`);
    lines.push(`// Re-generate: npx nest-scramble generate src --format client`);
    lines.push('');

    // Collect all DTO type names referenced in the scanned controllers so we can
    // emit placeholder interfaces at the top of the file.  Users replace these with
    // their real DTO imports; the generated code will still compile immediately.
    const dtoNames = this.collectDtoNames(controllers);
    if (dtoNames.size > 0) {
      lines.push('// ─── DTO type stubs ──────────────────────────────────────────────────────────');
      lines.push('// Replace these with your real DTO imports, e.g.:');
      lines.push('//   import { UserDto } from \'./src/dto/user.dto\';');
      lines.push('');
      for (const name of Array.from(dtoNames).sort()) {
        lines.push(`export interface ${name} { [key: string]: unknown; }`);
      }
      lines.push('');
    }

    // One class per controller
    for (const controller of controllers) {
      if (controller.methods.length === 0) continue;
      lines.push(...this.buildControllerClass(controller));
      lines.push('');
    }

    // Convenience factory that aggregates all clients
    lines.push(...this.buildAggregateClient(controllers));

    return lines.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private buildControllerClass(controller: ControllerInfo): string[] {
    const className = this.toClassName(controller.name) + 'Client';
    const lines: string[] = [];

    lines.push(`export class ${className} {`);
    lines.push(`  constructor(private readonly baseUrl: string) {}`);
    lines.push('');

    for (const method of controller.methods) {
      lines.push(...this.buildMethod(controller.path, method).map(l => `  ${l}`));
      lines.push('');
    }

    lines.push('}');
    return lines;
  }

  private buildMethod(controllerPath: string, method: MethodInfo): string[] {
    const lines: string[] = [];

    const pathParams = method.parameters.filter(p => p.parameterLocation === 'path' || p.decorator === 'Param');
    const queryParams = method.parameters.filter(p => p.parameterLocation === 'query' || p.decorator === 'Query');
    const bodyParam = method.parameters.find(p => p.parameterLocation === 'body' || p.decorator === 'Body');

    const returnTs = this.toTsType(method.returnType);
    const fnParams = this.buildFnParams(pathParams, queryParams, bodyParam);
    const fullRoute = this.joinPath(controllerPath, method.route);

    lines.push(`async ${method.name}(${fnParams}): Promise<${returnTs}> {`);

    // Build URL
    const urlExpr = this.buildUrlExpr(fullRoute, pathParams);
    if (queryParams.length > 0) {
      lines.push(`  const _url = new URL(\`\${this.baseUrl}${urlExpr}\`);`);
      for (const qp of queryParams) {
        const isOptional = qp.type.isOptional;
        if (isOptional) {
          lines.push(`  if (${qp.name} !== undefined) _url.searchParams.set('${qp.name}', String(${qp.name}));`);
        } else {
          lines.push(`  _url.searchParams.set('${qp.name}', String(${qp.name}));`);
        }
      }
    }

    const urlArg = queryParams.length > 0 ? '_url.toString()' : `\`\${this.baseUrl}${urlExpr}\``;

    // Build fetch call
    const httpMethod = method.httpMethod.toUpperCase();
    if (bodyParam) {
      lines.push(`  const _res = await fetch(${urlArg}, {`);
      lines.push(`    method: '${httpMethod}',`);
      lines.push(`    headers: { 'Content-Type': 'application/json' },`);
      lines.push(`    body: JSON.stringify(${bodyParam.name}),`);
      lines.push(`  });`);
    } else {
      if (httpMethod === 'GET') {
        lines.push(`  const _res = await fetch(${urlArg});`);
      } else {
        lines.push(`  const _res = await fetch(${urlArg}, { method: '${httpMethod}' });`);
      }
    }

    // Return handling
    if (returnTs === 'void') {
      lines.push(`  if (!_res.ok) throw new Error(\`${method.name} failed: \${_res.status}\`);`);
    } else {
      lines.push(`  if (!_res.ok) throw new Error(\`${method.name} failed: \${_res.status}\`);`);
      lines.push(`  return _res.json() as Promise<${returnTs}>;`);
    }

    lines.push('}');
    return lines;
  }

  private buildFnParams(
    pathParams: ParameterInfo[],
    queryParams: ParameterInfo[],
    bodyParam: ParameterInfo | undefined,
  ): string {
    const parts: string[] = [];

    for (const p of pathParams) {
      parts.push(`${p.name}: ${this.toTsType(p.type)}`);
    }
    for (const p of queryParams) {
      const opt = p.type.isOptional ? '?' : '';
      parts.push(`${p.name}${opt}: ${this.toTsType(p.type)}`);
    }
    if (bodyParam) {
      const opt = bodyParam.type.isOptional ? '?' : '';
      parts.push(`${bodyParam.name}${opt}: ${this.toTsType(bodyParam.type)}`);
    }

    return parts.join(', ');
  }

  private buildUrlExpr(route: string, pathParams: ParameterInfo[]): string {
    // Replace :param with ${param} template literal syntax
    let result = '/' + route.replace(/^\/+/, '').replace(/\/*$/, '');
    for (const p of pathParams) {
      result = result.replace(new RegExp(`:${p.name}`, 'g'), `\${${p.name}}`);
      // Also handle {param} style (OpenAPI normalised)
      result = result.replace(new RegExp(`\\{${p.name}\\}`, 'g'), `\${${p.name}}`);
    }
    return result;
  }

  private buildAggregateClient(controllers: ControllerInfo[]): string[] {
    const valid = controllers.filter(c => c.methods.length > 0);
    if (valid.length === 0) return [];

    const lines: string[] = [];
    lines.push('// ─── Aggregate client ───────────────────────────────────────────────────────');
    lines.push('export class ApiClient {');
    for (const c of valid) {
      const propName = this.toCamelCase(c.name.replace(/Controller$/i, ''));
      const className = this.toClassName(c.name) + 'Client';
      lines.push(`  readonly ${propName}: ${className};`);
    }
    lines.push('');
    lines.push('  constructor(baseUrl: string) {');
    for (const c of valid) {
      const propName = this.toCamelCase(c.name.replace(/Controller$/i, ''));
      const className = this.toClassName(c.name) + 'Client';
      lines.push(`    this.${propName} = new ${className}(baseUrl);`);
    }
    lines.push('  }');
    lines.push('}');
    return lines;
  }

  // ---------------------------------------------------------------------------
  // Type helpers
  // ---------------------------------------------------------------------------

  private collectDtoNames(controllers: ControllerInfo[]): Set<string> {
    const names = new Set<string>();
    const primitives = new Set(['string', 'number', 'boolean', 'any', 'void', 'unknown', 'object', 'never']);

    const visit = (t: AnalyzedType) => {
      const base = t.type.replace(/\[\]$/, '');
      if (!primitives.has(base) && /^[A-Z]/.test(base)) {
        names.add(base);
      }
      if (t.properties) {
        for (const p of t.properties) visit(p.type);
      }
    };

    for (const c of controllers) {
      for (const m of c.methods) {
        visit(m.returnType);
        for (const p of m.parameters) visit(p.type);
      }
    }

    return names;
  }

  private toTsType(t: AnalyzedType): string {
    const primitiveMap: Record<string, string> = {
      String: 'string', Number: 'number', Boolean: 'boolean',
      Date: 'string', Object: 'unknown',
    };

    let base = primitiveMap[t.type] ?? t.type;
    if (!base || base === '' || base === 'undefined' || base === 'null') base = 'unknown';

    return t.isArray ? `${base}[]` : base;
  }

  // ---------------------------------------------------------------------------
  // String helpers
  // ---------------------------------------------------------------------------

  private toClassName(name: string): string {
    // PascalCase — strip common suffixes first
    return name.charAt(0).toUpperCase() + name.slice(1);
  }

  private toCamelCase(name: string): string {
    return name.charAt(0).toLowerCase() + name.slice(1);
  }

  private joinPath(...parts: string[]): string {
    return parts
      .map(p => p.replace(/^\/+|\/+$/g, ''))
      .filter(Boolean)
      .join('/');
  }
}
